# Generated by Django 5.2.1 on 2025-06-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nível de Água',
                'verbose_name_plural': 'Níveis de Água',
                'db_table': 'nivel_agua',
            },
        ),
        migrations.CreateModel(
            name='VolumeChuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volume de Chuva',
                'verbose_name_plural': 'Volumes de Chuva',
                'db_table': 'volume_chuva',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('geojson', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'db_table': 'regiao',
                'indexes': [models.Index(fields=['numero'], name='idx_regiao_numero')],
            },
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('avaliar_risco', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nivel_agua', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.nivelagua')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='core.regiao')),
                ('volume_chuva', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.volumechuva')),
            ],
            options={
                'verbose_name': 'Medição',
                'verbose_name_plural': 'Medições',
                'db_table': 'medicao',
            },
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='core.regiao')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'db_table': 'cadastro',
            },
        ),
        migrations.CreateModel(
            name='RiscoHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.CharField(blank=True, max_length=500, null=True)),
                ('risco', models.BooleanField(default=False)),
                ('processamento_tempo', models.DecimalField(blank=True, decimal_places=3, help_text='Tempo processamento CNN em segundos', max_digits=5, null=True)),
                ('confianca_ia', models.DecimalField(blank=True, decimal_places=3, help_text='Nível de confiança da IA (0-1)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risco_humano', to='core.medicao')),
            ],
            options={
                'verbose_name': 'Risco Humano',
                'verbose_name_plural': 'Riscos Humanos',
                'db_table': 'risco_humano',
            },
        ),
        migrations.CreateModel(
            name='EnvioAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('envio_whats', models.BooleanField(default=False)),
                ('envio_email', models.BooleanField(default=False)),
                ('sucesso_whats', models.BooleanField(blank=True, null=True)),
                ('sucesso_email', models.BooleanField(blank=True, null=True)),
                ('erro_whats', models.TextField(blank=True, null=True)),
                ('erro_email', models.TextField(blank=True, null=True)),
                ('tentativas_whats', models.PositiveSmallIntegerField(default=0)),
                ('tentativas_email', models.PositiveSmallIntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recebidos', to='core.cadastro')),
                ('risco_humano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='core.riscohumano')),
            ],
            options={
                'verbose_name': 'Envio de Alerta',
                'verbose_name_plural': 'Envios de Alerta',
                'db_table': 'envio_alerta',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(unique=True)),
                ('descricao', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('tipo_alerta', models.CharField(max_length=50)),
                ('cnn_ativa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'indexes': [models.Index(fields=['cnn_ativa'], name='idx_status_cnn_ativa')],
            },
        ),
        migrations.AddField(
            model_name='riscohumano',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.status'),
        ),
        migrations.CreateModel(
            name='TextoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='core.status')),
            ],
            options={
                'verbose_name': 'Texto de Alerta',
                'verbose_name_plural': 'Textos de Alerta',
                'db_table': 'texto_alerta',
            },
        ),
        migrations.AddIndex(
            model_name='cadastro',
            index=models.Index(fields=['regiao'], name='idx_cadastro_regiao'),
        ),
        migrations.AddIndex(
            model_name='cadastro',
            index=models.Index(fields=['situacao'], name='idx_cadastro_situacao'),
        ),
        migrations.AddIndex(
            model_name='cadastro',
            index=models.Index(fields=['telefone'], name='idx_cadastro_telefone'),
        ),
        migrations.AddIndex(
            model_name='envioalerta',
            index=models.Index(fields=['data'], name='idx_envio_alerta_data'),
        ),
        migrations.AddIndex(
            model_name='envioalerta',
            index=models.Index(fields=['risco_humano'], name='idx_envio_alerta_risco'),
        ),
        migrations.AddIndex(
            model_name='envioalerta',
            index=models.Index(fields=['cadastro'], name='idx_envio_alerta_cadastro'),
        ),
        migrations.AddIndex(
            model_name='envioalerta',
            index=models.Index(fields=['sucesso_whats', 'sucesso_email'], name='idx_envio_alerta_sucesso'),
        ),
        migrations.AddIndex(
            model_name='riscohumano',
            index=models.Index(fields=['data'], name='idx_risco_humano_data'),
        ),
        migrations.AddIndex(
            model_name='riscohumano',
            index=models.Index(fields=['risco'], name='idx_risco_humano_risco'),
        ),
        migrations.AddIndex(
            model_name='riscohumano',
            index=models.Index(fields=['status'], name='idx_risco_humano_status'),
        ),
        migrations.AddIndex(
            model_name='textoalerta',
            index=models.Index(fields=['status'], name='idx_texto_alerta_status'),
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['data'], name='idx_medicao_data'),
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['regiao'], name='idx_medicao_regiao'),
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['avaliar_risco'], name='idx_medicao_risco'),
        ),
        migrations.AddIndex(
            model_name='medicao',
            index=models.Index(fields=['regiao', 'data'], name='idx_medicao_regiao_data'),
        ),
    ]
